### ISSUE TITLE
linux/arm64/v8 does not match the detected host platform linux/amd64

### ISSUE THREAD

**Issue by salatielosorno** [uraimo/run-on-arch-action#109]
I am getting the following message:

```bash
Warning: rning] The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64) and no specific platform was requested
```
<img width="1022" alt="arm64-issue" src="https://user-images.githubusercontent.com/34631693/213357866-855340f5-7732-4f16-bc44-cf9ab8f4817d.png">

Here is my `yml` file:
```yml
name: Build and Release
on:
  push:
    branches:
      - release/V1.0.0
    tags:
      - v*

jobs:
  build_on_linux:
    name: Linux (${{ matrix.os }} - ${{ matrix.arch }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
        arch: [ aarch64 ]
        distro: [ ubuntu20.04 ]
    steps:
      - uses: actions/checkout@v2
      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        id: runcmd
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}
          # Set an output parameter `uname` for use in subsequent steps
          run: |
            uname -a
            echo ::set-output name=uname::$(uname -a)
      - name: Install NodeJS and NPM
        run: sudo apt install nodejs -y && sudo apt install npm -y
      - name: NPM Version
        run: npm --version
      - name: install dependencies
        run: npm install
      - name: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run publish
```

The workflows runs ok. However I need to build my application using `arm64`arch. Any idea what is happening?
