### ISSUE TITLE
The process '/home/runner/work/_actions/uraimo/run-on-arch-action/v2/src/run-on-arch.sh' failed

### ISSUE THREAD

**Issue by try-agaaain** [uraimo/run-on-arch-action#114]
I want to build the project on the aarch64 platform, but the following error occurs:

![image](https://user-images.githubusercontent.com/52828870/223714880-e2fbccb4-4ecb-46d7-8c5a-9941cd61f66e.png)

Weird, the platform I set is aarch64, but it shows x86_64 here?

Below is my workflow:
```yaml
on: [push, pull_request]

jobs:
  build_job:
    # The host should always be linux
    runs-on: ubuntu-22.04
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}

    # Run steps on a matrix of 4 arch/distro combinations
    strategy:
      matrix:
        include:
          - arch: aarch64
            distro: ubuntu22.04
    steps:
      - uses: actions/checkout@v3
      - uses: uraimo/run-on-arch-action@v2
        name: Build artifact
        id: build
        with:
          arch: aarch64
          distro: ubuntu22.04

          # Not required, but speeds up builds
          githubToken: ${{ github.token }}

          # Create an artifacts directory
          setup: |
            echo "my info: " `uname -a`

          # Mount the artifacts directory as /artifacts in the container
          dockerRunArgs: |
            -v /usr/bin/:/usr/bin/
          install: |
            echo "my info: " `uname -a`
            apt-get update && \
            apt-get install -y --no-install-recommends libelf1 libelf-dev \
                zlib1g-dev clang llvm libclang-13-dev make cmake git cargo wget tar curl && \
            apt-get install -y --no-install-recommends ca-certificates	&& \
            update-ca-certificates	&& \
            apt-get clean && \
            curl https://sh.rustup.rs -sSf | sh -s -- -y	&& \
            rm -rf /var/lib/apt/lists/*
            mkdir /src && cd /src
            git clone https://github.com/eunomia-bpf/eunomia-bpf.git && cd eunomia-bpf
            git submodule update --init --recursive --remote
            echo "my info: get the whole repo!"
            cd ecli && make build
            cp /src/eunomia-bpf/ecli/build/bin/Release/ecli /usr/bin/

          # Pass some environment variables to the container
          env: | # YAML, but pipe character is necessary
            artifact_name: git-${{ matrix.distro }}_${{ matrix.arch }}

          # The shell to run commands with in the container
          shell: /bin/sh

          # Produce a binary artifact and place it in the mounted volume
          run: |
            ls -af /usr/bin/ecli
```
