### ISSUE TITLE
Error while setting up Go

### ISSUE THREAD

**Issue by sunilkumardash9** [uraimo/run-on-arch-action#125]
while installing Go  from ppa:longsleep/golang-backports  I get this error: /root/run-on-arch-install.sh: line 6:  : command not found

But I don't get this error while installing from ubuntu's repo it works fine.

```
run_on_arm64:
      runs-on: ubuntu-latest
      steps:
       - uses: actions/checkout@v3

       - name: Set up Go
         uses: actions/setup-go@v3
         with:
           go-version: 1.19
         
       - name: Run on aarch64
         uses: uraimo/run-on-arch-action@v2
         with:
          arch: aarch64
          distro: ubuntu_latest
          githubToken: ${{ github.token }}
          install: |
            apt-get update && \
            apt-get install -y software-properties-common && \
            add-apt-repository ppa:longsleep/golang-backports -y && \    
            apt-get install golang-1.19
            
          run: |
            go build -buildvcs=false ./...
            go test -v ./... 
```

Is there something I am missing?
