### ISSUE TITLE
 Create new alpine targets, issue on alpine_latest distro.

### ISSUE THREAD

**Issue by RaulTrombin** [uraimo/run-on-arch-action#143]
Hey!

I'm using the action to run some test right after compile some Python whells.

action:
```
     - uses: uraimo/run-on-arch-action@v2.6.0
      if: matrix.libc == 'musllinux_1_1'
      name: Install built wheel musl
      with:
        arch: ${{ matrix.target}}
        distro: alpine_latest
        githubToken: ${{ github.token }}
        install: |
          apk add py3-pip
          pip3 install -U pip
        run: |
          pip3 install package_whell --no-index --find-links dist/ --force-reinstall
```

It was working till January, then started to break CI actions with this error:

```
  ------
  Dockerfile.armv7.alpine_latest:4
  --------------------
     2 |     
     3 |     COPY ./run-on-arch-install.sh /root/run-on-arch-install.sh
     4 | >>> RUN chmod +x /root/run-on-arch-install.sh && /root/run-on-arch-install.sh
     5 |     
  --------------------
  ERROR: failed to solve: process "/bin/sh -c chmod +x /root/run-on-arch-install.sh && /root/run-on-arch-install.sh" did not complete successfully: exit code: 1
  Error: The process '/home/runner/work/_actions/uraimo/run-on-arch-action/v2.6.0/src/run-on-arch.sh' failed with exit code 1
```

I think it's related to the alpine latest version, 
If I want to use some previous version and freeze it, Do I need to create this manually?
[v3.18](https://dl-cdn.alpinelinux.org/alpine/v3.18/)
