### ISSUE TITLE
Where to find gnu compiler?

### ISSUE THREAD

**Issue by peterzheng98** [uraimo/run-on-arch-action#15]
Where to find gcc in the image?

**Comment by uraimo** [comment]
Hi, the barebones base image doesn't have a compiler, you'll have to install it (build-essential on Ubuntu) by yourself as first step of your `run` section, e.g.:

```
on: [push]

jobs:
  armv7_job:
    runs-on: ubuntu-18.04
    name: Build on ARMv7 
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: uraimo/run-on-arch-action@v1.0.9
        id: runcmd
        with:
          architecture: armv7
          distribution: ubuntu18.04
          run: |
            apt install build-essential
            uname -a
```
