### ISSUE TITLE
Ubuntu 20.04 no longer works: "ERROR: failed to solve: arm64v8/ubuntu:20.04: failed to resolve source metadata"

### ISSUE THREAD

**Issue by eed3si9n** [uraimo/run-on-arch-action#155]
(I'm aware of #152. This issue is filed partly so it would be indexed in case others may find this useful)

## steps

The following setup used to work:

```yaml
      - name: Build Linux aarch64
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: aarch64
          distro: ubuntu20.04

          # Speeds up builds per the run-on-arch-action README
          githubToken: ${{ github.token }}
```

## problem

Build container phase fails with the following:

```
#2 [internal] load metadata for docker.io/arm64v8/ubuntu:20.04
  #2 ERROR: no match for platform in manifest: not found
  ------
   > [internal] load metadata for docker.io/arm64v8/ubuntu:20.04:
  ------
  Dockerfile.aarch64.ubuntu20.04:1
  --------------------
     1 | >>> FROM arm[64](https://github.com/sbt/sbtn-dist/actions/runs/11420327751/job/31775899476#step:4:65)v8/ubuntu:20.04
     2 |     
     3 |     COPY ./run-on-arch-install.sh /root/run-on-arch-install.sh
  --------------------
  ERROR: failed to solve: arm64v8/ubuntu:20.04: failed to resolve source metadata for docker.io/arm64v8/ubuntu:20.04: no match for platform in manifest: not found
  Error: The process '/home/runner/work/_actions/uraimo/run-on-arch-action/v2/src/run-on-arch.sh' failed with exit code 1
```

## workaround

Following https://github.com/uraimo/run-on-arch-action/issues/152 and other PRs linked to 152, the workaround apparently is:

```yaml
      - name: Build Linux aarch64
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: none
          distro: none
          base_image: '--platform=linux/aarch64 ubuntu:20.04'
```

## expectation

Would it be possible to absorb this in this action, or otherwise, please document this in the README.

**Comment by charliermarsh** [comment]
Any idea what changed to cause these sudden failures?

**Comment by eed3si9n** [comment]
I think it's something to do with the build process change in https://github.com/docker-library/official-images. See for example https://github.com/docker-library/python/issues/933:

> We've been slowly moving Official Images to a new build process and moved `python` yesterday, so now the arch-specific namespaces are an image index because they include attached provenance/sbom metedata.

**Comment by uraimo** [comment]
> Any idea what changed to cause these sudden failures?

They started generating the upstream images as they should always have, without including an implicit platform in each dockerfile, but specifying a specific platform is now required when creating the image.

Since I can see reports for some of the major platforms I updated the default dockerfiles to include the workaround and the tests look green now. I will also add a new PLATFORM parameter for those using directly the base_image configuration since as many have pointed out it's now necessary.

In hindsight, providing a set of default "verified" images to make it easier for the users was not a good idea, it introduced a dependency on the upstream images, that the maintainers were able to update at will introducing regressions.

Once the tests are done I will tag a new release.

**Comment by uraimo** [comment]
Published 2.8.0 with the updated default Dockerfiles.

**Comment by konstin** [comment]
In https://github.com/uraimo/run-on-arch-action/commit/96c27aa6978f736220aea94414920135028189be#diff-e1ee779207cb43290a986a3da96826a65bcfa58d723177caca6cc6eaa091f4a8R1 there's a typo, it say `FROM --platform=linux/arm64 rm64v8/ubuntu:20.04` (https://github.com/astral-sh/uv/actions/runs/11431169900/job/31813036963)

**Comment by eed3si9n** [comment]
I can confirm that the original YAML setup works again with the latest:

```yaml
      - name: Build Linux aarch64
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: aarch64
          distro: ubuntu20.04

          # Speeds up builds per the run-on-arch-action README
          githubToken: ${{ github.token }}
```

Thanks @uraimo and others!
