### ISSUE TITLE
base_image parameter is not working

### ISSUE THREAD

**Issue by lbr38** [uraimo/run-on-arch-action#164]
Hello

I got the following error when trying to use the `base_image` parameter:

```
Error: run-on-arch: If arch and distro are not specified, base_image is required.
```

![Image](https://github.com/user-attachments/assets/87ff7c87-d920-4398-ac0c-611ed5dcf2b3)

The config is:

![Image](https://github.com/user-attachments/assets/eaee7785-0a42-4854-b3e1-8d344be744e1)

Is there something I am missing?

Thanks for the help.

**Comment by martin-g** [comment]
> Is there something I am missing?

You missed to paste the action configuration. You imaged only the matrix config, but whether and how this matrix is being used is unknown to us.
Better link to your project.

**Comment by lbr38** [comment]
My project is private. I just tried with the example in the README and got this error. 

Only the arch+distro combo are working but as soon as I use the base_image param with arch and distro set to none, it fails.

Can you test the README example on your side?

**Comment by uraimo** [comment]
Please specify a specific tag for the busybox image like `riscv64/busybox:stable` or use something like `riscv64/ubuntu:22.04`, I've added the latter to our CI and it works.

**Comment by lbr38** [comment]
Thanks for the help, I retried with the updated README example and still got the same error unfortunately

![Image](https://github.com/user-attachments/assets/c4a98169-d855-40ee-93cd-ecda8cb6c931)

Here is the complete workflow. But this is basically the exact copy of the README example:

```
on: [push, pull_request]

jobs:
  build_job:
    # The host should always be linux
    runs-on: ubuntu-22.04
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}

    # Run steps on a matrix of 4 arch/distro combinations
    strategy:
      matrix:
        include:
          - arch: aarch64
            distro: ubuntu22.04
          - arch: aarch64
            distro: bullseye 
          - arch: ppc64le
            distro: alpine_latest
          - arch: none
            distro: none
            base_image: --platform=linux/riscv64 riscv64/ubuntu:22.04
    steps:
      - uses: actions/checkout@v4
      - uses: uraimo/run-on-arch-action@v3
        name: Build artifact
        id: build
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}

          # Not required, but speeds up builds
          #githubToken: ${{ github.token }}

          # Create an artifacts directory
          setup: |
            mkdir -p "${PWD}/artifacts"

          # Mount the artifacts directory as /artifacts in the container
          dockerRunArgs: |
            --volume "${PWD}/artifacts:/artifacts"

          # Pass some environment variables to the container
          env: | # YAML, but pipe character is necessary
            artifact_name: git-${{ matrix.distro }}_${{ matrix.arch }}

          # The shell to run commands with in the container
          shell: /bin/sh

          # Install some dependencies in the container. This speeds up builds if
          # you are also using githubToken. Any dependencies installed here will
          # be part of the container image that gets cached, so subsequent
          # builds don't have to re-install them. The image layer is cached
          # publicly in your project's package repository, so it is vital that
          # no secrets are present in the container state or logs.
          install: |
            case "${{ matrix.distro }}" in
              ubuntu*|jessie|stretch|buster|bullseye)
                apt-get update -q -y
                apt-get install -q -y git
                ;;
              fedora*)
                dnf -y update
                dnf -y install git which
                ;;
              alpine*)
                apk update
                apk add git
                ;;
            esac

          # Produce a binary artifact and place it in the mounted volume
          run: |
            cp $(which git) "/artifacts/${artifact_name}"
            echo "Produced artifact at /artifacts/${artifact_name}"

      - name: Show the artifact
        # Items placed in /artifacts in the container will be in
        # ${PWD}/artifacts on the host.
        run: |
          ls -al "${PWD}/artifacts"
```
