### ISSUE TITLE
Is there any example or tip to run it with a cache folder for long builds ?

### ISSUE THREAD

**Issue by patrickelectric** [uraimo/run-on-arch-action#34]

**Comment by uraimo** [comment]
Hi, you could cache "something", leveraging the install option:

> install: Shell commands to execute in the container as part of docker build, such as installing dependencies. This speeds up subsequent builds if githubToken is also used, but note that the image layer will be publicly available in your projects GitHub Package Registry, so make sure the resulting image does not have any secrets cached in logs or state.

But I'm not really sure if that's the better option in your case (would require a double build, the first one in "install" to build the initial cache) but can't think of any easy alternative right now.

**Comment by elijahr** [comment]
I think you could use actions/cache and mount the restored cache in a volume:

```yml
- name: Restore cache
  uses: actions/cache@v2
  with:
    path: |
      build-cache
    key: some-key

- uses: uraimo/run-on-arch-action@v2.0.5
  name: Build

  ...

  # Create a build-cache directory
  setup: |
    mkdir -p "${PWD}/build-cache"

  # Mount the build-cache directory as /build-cache in the container
  dockerRunArgs: |
    --volume "${PWD}/build-cache:/build-cache"

  ...
```
