### ISSUE TITLE
Using `act` to test an action locally fails

### ISSUE THREAD

**Issue by tcdude** [uraimo/run-on-arch-action#42]
I would like to test a new workflow using this action on my local machine using `nektos/act`, but even with the simple example listed in the README, it fails with this output:
```
| WARNING: The requested image's platform (linux/arm) does not match the detected host platform (linux/amd64) and no specific platform was requested
| docker: Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: exec: "/actions/uraimo-run-on-arch-action@v2.0.5/src/run-on-arch-commands.sh": stat /actions/uraimo-run-on-arch-action@v2.0.5/src/run-on-arch-commands.sh: no such file or directory: unknown.
[Linux-ARM/Build on ubuntu-18.04 armv7]   ❗  ::error::The process '/actions/uraimo-run-on-arch-action@v2.0.5/src/run-on-arch.sh' failed with exit code 127
[Linux-ARM/Build on ubuntu-18.04 armv7]   ❌  Failure - Run commands
DEBU[0023] exit with `FAILURE`: 1                       
DEBU[0023] exit with `FAILURE`: 1                       
Error: exit with `FAILURE`: 1
```

I realize that this might not be the intended way to running this action, but I would really like to get this working together with `act`.

I also tried to use the latest release `2.0.9` and I tried using different arch/distro combinations. Any help debugging the problem would be greatly appreciated.

**Comment by elijahr** [comment]
@tcdude what is your workflow config yml, and what `act` command are you running?

**Comment by tcdude** [comment]
Here's the yml (*I stripped the end, because it's not part of the issue*):
```yml
name: Linux-ARM

on: push

jobs:
  build_job:
    runs-on: ubuntu-18.04
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}

    # Run steps for both armv6 and aarch64
    strategy:
      matrix:
        include:
          - arch: aarch64
            distro: stretch
          - arch: armv6
            distro: jessie

    steps:
      - uses: actions/checkout@v2.1.0
      - uses: uraimo/run-on-arch-action@v2.0.9
        name: Build artifact
        id: build
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}

          # Not required, but speeds up builds
          githubToken: ${{ github.token }}

          # Create an artifacts directory
          setup: |
            mkdir -p "${PWD}/artifacts"

          # Mount the artifacts directory as /artifacts in the container
          dockerRunArgs: |
            --volume "${PWD}/artifacts:/artifacts"

          # Pass the correct artifact name
          env: | # YAML, but pipe character is necessary
            artifact_name: krafix-linux-${{ matrix.arch }}

          # The shell to run commands with in the container
          shell: /bin/bash

          # Install some dependencies in the container. This speeds up builds if
          # you are also using githubToken. Any dependencies installed here will
          # be part of the container image that gets cached, so subsequent
          # builds don't have to re-install them. The image layer is cached
          # publicly in your project's package repository, so it is vital that
          # no secrets are present in the container state or logs.
          install: |
              apt-get update -y -q
              apt-get upgrade -y -q
              apt-get install -y -q libasound2-dev libxinerama-dev libgl1-mesa-dev libxi-dev git build-essential

          # Produce a binary artifact and place it in the mounted volume
          run: |
            echo " * Get Submodules"
            git submodule update --init --recursive

            echo " * Get Kinc"
            git clone --recursive https://github.com/Kode/Kinc.git
            echo " * Get Node.js"
            git clone https://github.com/Kode/nodejs_bin.git --depth 1
            echo " * Setup Node.js"
            nodejs_bin/copysysbin.sh
            echo " * Compile"
            nodejs_bin/node Kinc/make --compile  || nodejs_bin/node-linuxarm Kinc/make --compile
            echo " * Copying artifact"
            cp build/Release/krafix "/artifacts/${artifact_name}"

...
# More stuff happening, but not using run-on-arch-action related elements

```

And the act command was simply `act -j build_job`
