### ISSUE TITLE
Support for whole jobs

### ISSUE THREAD

**Issue by Gerschtli** [uraimo/run-on-arch-action#6]
Hey, I just wondered if there could be a way to emulate aarch64 for all steps like

```yaml
jobs:
  build:
    container: name-of/container-image

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
```

I would love to run actions on this container provided by this repo!
