### ISSUE TITLE
Need alpine_edge; Dockerfile.aarch64.alpine_edge does not exist

### ISSUE THREAD

**Issue by probonopd** [uraimo/run-on-arch-action#78]
In my [build.yaml](https://github.com/probonopd/static-tools/blob/01fa56e14a88a2f41219650ff4895e8fdfcc8d13/.github/workflows/build.yaml) I am using

```
      uses: uraimo/run-on-arch-action@v2
      with:
        arch: ${{ matrix.qemu_arch }}
        distro: alpine_edge
```

because I need fuse3 wich is only in the edge branch of Alpine Linux (I was told that fuse2 is no longer maintained and should not be used anymore).

Getting

```
build (aarch64, aarch64)
run-on-arch: /home/runner/work/_actions/uraimo/run-on-arch-action/v2/Dockerfiles/Dockerfile.aarch64.alpine_edge does not exist.
build (armv7, armhf)
run-on-arch: /home/runner/work/_actions/uraimo/run-on-arch-action/v2/Dockerfiles/Dockerfile.armv7.alpine_edge does not exist.
```

Can alpine_edge be enabled please?
