### ISSUE TITLE
Volume is not mounted

### ISSUE THREAD

**Issue by jokaorgua** [uraimo/run-on-arch-action#79]
Hello.

Could anyone guide me how to mount current directory into the aarch64 container?

I'm trying to do that with 

```
dockerRunarg: |
  --volume "${PWD}:/app"
```

but the volume is not mounted

```
Run uraimo/run-on-arch-action@v2
Configuring Docker for multi-architecture support
/home/runner/work/_actions/uraimo/run-on-arch-action/v2/src/run-on-arch.sh /home/runner/work/_actions/uraimo/run-on-arch-action/v2/Dockerfiles/Dockerfile.aarch64.ubuntu20.04 run-on-arch-jokaorgua-for-files-ci-aarch64-ubuntu20-04 --volume ${PWD}:/app
Build container
  GitHub token provided, caching to ghcr.io/jokaorgua/for_files/run-on-arch-jokaorgua-for-files-ci-aarch64-ubuntu20-04
  WARNING! Your password will be stored unencrypted in /home/runner/.docker/config.json.
  Configure a credential helper to remove this warning. See
  https://docs.docker.com/engine/reference/commandline/login/#credentials-store
  
  Login Succeeded
  Error response from daemon: manifest unknown
  Sending build context to Docker daemon  61.44kB
  
  Step 1/3 : FROM arm64v8/ubuntu:20.04
  20.04: Pulling from arm64v8/ubuntu
  d4ba87bb7858: Pulling fs layer
  d4ba87bb7858: Verifying Checksum
  d4ba87bb7858: Download complete
  d4ba87bb7858: Pull complete
  Digest: sha[25](https://github.com/jokaorgua/for_files/runs/6324683489?check_suite_focus=true#step:4:25)6:ca83774d06420ceb4682ef73bd9cbbfc38a97a[27](https://github.com/jokaorgua/for_files/runs/6324683489?check_suite_focus=true#step:4:27)e061b578547a6761206658b9
  Status: Downloaded newer image for arm64v8/ubuntu:20.04
   ---> db1bc6aa58da
  Step 2/3 : COPY ./run-on-arch-install.sh /root/run-on-arch-install.sh
   ---> 95ef0[31](https://github.com/jokaorgua/for_files/runs/6324683489?check_suite_focus=true#step:4:31)9085f
  Step 3/3 : RUN chmod +x /root/run-on-arch-install.sh && /root/run-on-arch-install.sh
  Warning: rning] The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64) and no specific platform was requested
   ---> Running in 55c58bc0ca7a
  /root/run-on-arch-install.sh: line 4: cd: /app: No such file or directory
```

Here is my workflow
```
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    # This workflow contains a single job called "build"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: aarch64
            distro: ubuntu20.04
            build-targets: "deb"
            os: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout branch
      - run: echo ${PWD}
      - uses: uraimo/run-on-arch-action@v2
        name: setup aarch container
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}
          # Not required, but speeds up builds
          githubToken: ${{ github.token }}
          shell: /bin/bash
          # Mount the artifacts directory as /artifacts in the container
          dockerRunArgs: |
            --volume "${PWD}:/app"
          install: |
            cd /app
            ls -la
            apt update
            apt install -y curl ruby-dev build-essential
            gem i fpm -f
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
            source ~/.nvm/nvm.sh
            nvm use v16.13.2
            nvm installnvm
          run: |
            uname -a
            node --version
            nvm --version
```
