### ISSUE TITLE
aarch64 debian error  ##[error]The process '/home/runner/work/_actions/uraimo/run-on-arch-action/v1.0.7/src/run-on-arch.sh' failed with exit code 125 ##[error]Node run failed with exit code 1

### ISSUE THREAD

**Issue by yjcn** [uraimo/run-on-arch-action#8]
buster aarch64 error 
this is the workflow file.
```
on: 
  watch:
    types: [started]

jobs:
  armv7_job:
    runs-on: ubuntu-18.04
    name: Build on ARMv7 
    steps:
      - uses: actions/checkout@v1.0.0
      - uses: uraimo/run-on-arch-action@v1.0.7
        id: runcmd
        with:
          architecture: aarch64
          distribution: buster
          additionalArgs: <additional args for architecture specific docker, optional>
          run: |
            uname -a
            echo ::set-output name=uname::$(uname -a)
      - name: Get the output
        run: |
            echo "The uname output was ${{ steps.runcmd.outputs.uname }}"
```
![图片](https://user-images.githubusercontent.com/8858803/74317362-3eba3a00-4db6-11ea-8975-a04e399382c9.png)
this is job log https://github.com/yjcn/testarch/actions/runs/38046045
